name: Node.js CI

on:
  push:
    branches: [ main ] # Trigger the workflow on pushes to the main branch
  pull_request:
    branches: [ main ] # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # Check out the repository

    - name: Setup Node.js
      uses: actions/setup-node@v2 # Set up Node.js environment
      with:
        node-version: '14' # Specify the Node.js version

    - name: Install Dependencies
      run: npm install # Install Node.js dependencies

    - name: Run Tests
      run: npm test # Execute tests
