name: Node.js CI/CD

on:
  push:
    branches: [main] # Trigger the workflow on pushes to the main branch
  pull_request:
    branches: [main] # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # Check out the repository

    - name: Setup Node.js
      uses: actions/setup-node@v2 # Set up Node.js environment
      with:
        node-version: '14' # Specify the Node.js version

    - name: Install Dependencies
      run: npm install # Install Node.js dependencies

    - name: Run Tests
      run: npm test # Execute tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # Check out the repository

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AKIAZHRQUH2G7APNBIGZ }}
        aws-secret-access-key: ${{ secrets.rppg404jFvN/3dxBlmb4q5G53yM6x54s01E6Lr50 }}
        aws-region: your-aws-region

    - name: Deploy to AWS Lightsail
      run: |
        aws lightsail push-container-image --service-name your-lightsail-service-name --image your-docker-image-url

